development:
  adapter: postgresql
  encoding: unicode
  database: oly_training
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5433


test:
  adapter: postgresql
  encoding: unicode
  database: oly_training_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5433
